### PR TITLE
Add more facts for consideration

### PR DESCRIPTION
**Pull request by roskelleycj**
As I pondered this it occurred to me that we would likely need the current parameters as well as the proposed parameters to be compared.  (We might still need the current values for the resources too.)

These commits add the needed facts that can be used in the rules.

### CODE REVIEW

**Comment by woodstock3368** [comment]
Again, I would probably squash this down.

**Comment by woodstock3368** [comment]
PS.  just an idea.  You don't need to merge it.  Just wanted to communicate the thoughts/needs.

**Comment by woodstock3368** [comment]
As I ponder this and compare it to our experiences with RDS, I wonder if we shouldn't also include the ActualValues in the set of Facts?  This would then allow for some similar comparisons that we have done with RDS for other AWS resource types.

Of course, as I begin to think about this possibility it raises the likelihood that our abstraction (CFN only) would be insufficient, as ActualValues as Facts would require us expect/provide some form of a scripting engine that could be called with the name of the AWS Resource return a map of the Actual Values.  This isn't impossible, just enlarges the scope beyond a CFN only experience.  I wonder if we shouldn't consider the possibility?  Indeed, given how very little of our provisioning is performed in CFN it might be wise to consider this possibility.  As I'm not entirely sure that CFN will be able to support the 80% cases. 

Thoughts?

**Comment by roskelleycj** [comment]
It is has been a while, not sure that this is needed anymore.

**Pull request closed without merging**
